# Generated by Django 5.0.4 on 2024-04-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'RegistrationCodes',
            },
        ),
    ]
