# Generated by Django 5.0.4 on 2024-04-27 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0006_alter_shippingaddress_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentcard',
            name='billing_addr',
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='address1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='address2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='card_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='zipcode',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BillingAddress',
        ),
    ]
