# Generated by Django 5.0.4 on 2024-04-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0007_remove_paymentcard_billing_addr_paymentcard_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcard',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
